version = "2"

[buildpack]
  id = "io.buildpacks.nodejs"
  name = "Node.js Buildpack"
  version = "0.0.9"

  ## top-level order or path definition is optional
  ## top-level order or path definition is the default entrypoint if defined
[[order]]
    group = [
      { id = "io.buildpacks.nodejs#engine" },
      { id = "io.buildpacks.nodejs#npm" },
      { id = "i.dont.live.here", version = "0.2.0"} # on builder
    ]

## OR
## path = "."

[[modules]]
    id = "npm"
    name = "NPM Buildpack"
    path = "./npm-cnb/"
    [buildpack.modules.metdata]
    # ...
[[modules]]
    id = "engine"
    name = "Node Engine Buildpack"
    path = "./node-cnb/"
    [buildpack.modules.metdata]
    # ...

[[stacks]]
id = "io.buildpacks.stacks.bionic"
